const data = [
    {
        url:"video/video01.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video02.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video03.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video04.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video05.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video06.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video07.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video08.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video09.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video10.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video11.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video12.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video13.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video14.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video15.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video16.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video17.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video18.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video19.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video20.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video21.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video22.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video23.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video24.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video25.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },
    {
        url:"video/video26.mp4",
        channel:"aniket2304",
        description:"THis is a description",
        song:"Ik Mulaquat",
        likes:"123",
        messages:"456",
        shares:"234",
    },

    
];

export default data;